export const START_GET_PLAYERS = "START_GET_PLAYERS";
export const ERROR_GET_PLAYERS = "ERROR_GET_PLAYERS";
export const SUCCESSFUL_GET_PLAYERS = "SUCCESSFUL_GET_PLAYERS";

export const START_GET_PLAYERS_BY_TEAM = "START_GET_PLAYERS_BY_TEAM";
export const ERROR_GET_PLAYERS_BY_TEAM = "ERROR_GET_PLAYERS_BY_TEAM";
export const SUCCESSFUL_GET_PLAYERS_BY_TEAM = "SUCCESSFUL_GET_PLAYERS_BY_TEAM";

export const START_GET_PLAYER_SELECTED = "START_GET_PLAYER_SELECTED";
export const ERROR_GET_PLAYER_SELECTED = "ERROR_GET_PLAYER_SELECTED";
export const SUCCESSFUL_GET_PLAYER_SELECTED = "SUCCESSFUL_GET_PLAYER_SELECTED";

export const START_GET_PLAYER_STATUS = "START_GET_PLAYER_STATUS";
export const ERROR_GET_PLAYER_STATUS = "ERROR_GET_PLAYER_STATUS";
export const SUCCESSFUL_GET_PLAYER_STATUS = "SUCCESSFUL_GET_PLAYER_STATUS";

export const START_GET_PLAYERS_BY_TEAM_TABLE =
	"START_GET_PLAYERS_BY_TEAM_TABLE";
export const ERROR_GET_PLAYERS_BY_TEAM_TABLE =
	"ERROR_GET_PLAYERS_BY_TEAM_TABLE";
export const SUCCESSFUL_GET_PLAYERS_BY_TEAM_TABLE =
	"SUCCESSFUL_GET_PLAYERS_BY_TEAM_TABLE";
