export const START_GET_PLAYERS = "START_GET_PLAYERS";
export const ERROR_GET_PLAYERS = "ERROR_GET_PLAYERS";
export const SUCCESSFUL_GET_PLAYERS = "SUCCESSFUL_GET_PLAYERS";

export const START_GET_PLAYERS_BY_TEAM = "START_GET_PLAYERS_BY_TEAM";
export const ERROR_GET_PLAYERS_BY_TEAM = "ERROR_GET_PLAYERS_BY_TEAM";
export const SUCCESSFUL_GET_PLAYERS_BY_TEAM = "SUCCESSFUL_GET_PLAYERS_BY_TEAM";
