export const START_GET_TEAMS = "START_GET_TEAMS";
export const ERROR_GET_TEAMS = "ERROR_GET_TEAMS";
export const SUCCESSFUL_GET_TEAMS = "SUCCESSFUL_GET_TEAMS";

export const START_GET_TEAM_SELECTED = "START_GET_TEAM_SELECTED";
export const ERROR_GET_TEAM_SELECTED = "ERROR_GET_TEAM_SELECTED";
export const SUCCESSFUL_GET_TEAM_SELECTED = "SUCCESSFUL_GET_TEAM_SELECTED";
